---
- name: Test playbook for ldap_certs
  hosts: test
  remote_user: root
  roles:
    - sudo
    - ldap_certs
  vars:
    ldap_certs:
      - { exists: 'true', gets_hashlink: 'false', file: '../../../company/ldap_certs-files/CA1-CA1.crt' }
      - { exists: 'true', gets_hashlink: 'false', file: '../../../company/ldap_certs-files/CA2-SubCA.crt' }
      - { exists: 'true', gets_hashlink: 'true', file: '../../../company/ldap_certs-files/certs-example-2016.pem' }
