---
- name: Test playbook for sudo
  hosts: test
  remote_user: root
  roles:
    - sudo
  vars:
    sudo_strings
      - { priority: 40, name: 'admins-do-all', content: 'User_Alias ADMINS = bgstack15, bgstack15, user16, user16' }
      - { priority: 41, name: 'a', content: 'ADMINS ALL=(ALL)  ALL' }
    sudo_files
      - { file: '../../../company/sudo-files/40_bgstack15' }
